services:
  it-tools:
    container_name: it-tools-subfolder
    image: ghcr.io/sharevb/it-tools:baseurl-it-tools
    pull_policy: always
    restart: unless-stopped
  nginx-reverse-proxy:
    image: nginx:alpine
    depends_on:
      - it-tools
    volumes:
      - "./nginx.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - 80:80